server:
  port: 8081
spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/wxvedio?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
mybatis:
  type-aliases-package: com.imooc.pojo
 # configuration: true  #使用通用mapper自定义的方法要开启驼峰命名法
  ##jwt配置
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800